global:
  environment: staging

app:
  replicas: 2
  image:
    tag: staging
  service:
    type: NodePort
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 400m
      memory: 512Mi

gateway:
  enabled: true
  className: kgateway-staging-class

mongodb:
  pvHostPath: "/mnt/data/mongodb-staging"

